
class Constants:
    PATH_TO_YOLO_V2 = './models/yolov2'

    PATH_TO_YOLOV2_MODEL_STORAGE = f'{PATH_TO_YOLO_V2}/model_storage'
    PATH_TO_PRETRAINED_YOLO_V2_MODEL = f'{PATH_TO_YOLOV2_MODEL_STORAGE}/yolov2_coco.h5'
    PATH_TO_PRETRAINED_YOLO_V2_MODEL_FULLY_CONV = f'{PATH_TO_YOLOV2_MODEL_STORAGE}/yolov2_coco_fully_conv.h5'

    PATH_TO_YOLO_V2_CFG = f'{PATH_TO_YOLOV2_MODEL_STORAGE}/yolov2.cfg'
    PATH_TO_YOLO_V2_COCO_WEIGHTS = f'{PATH_TO_YOLOV2_MODEL_STORAGE}/yolov2.weights'
    PATH_TO_YOLO_V2_COCO_ANCHORS = f'{PATH_TO_YOLOV2_MODEL_STORAGE}/yolo_anchors.txt'
